name: Run Azure Login with the Service Principal secret
on: [push]

jobs:
  azurelogin:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

#fflint 
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TFLint
        uses: pauloconnor/tflint-action@v0.0.2 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tflint_path: environments/
            tflint_recurse: true
            tflint_changed_only: false
            tflint_extra_options: --output json
            tflint_enabled_rules:
              terraform_required_providers
              terraform_standard_module_structure
            tflint_disabled_rules:
              terraform_deprecated_interpolation

#tfsec
  tfsec:
   name: TFsec action
   runs-on: ubuntu-latest
    steps:
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
        working_directory: .
        version: v1.0.3
        format: default
        github_token:  ${{ secrets.GITHUB_TOKEN }}
  
          
    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

     # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

     # On push to "master", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply -auto-approve
